window.texts = window.texts || {
    CheckoutTitle: "الدفع",
    UpdateOrder: "تعديل الطلب",
    Hot: "حار",
    SpecialOrder: "طلب خاص",
    Item: "الصنف",
    Quantity: "الكمية",
    Price: "السعر",
    Total: "الإجمالي",
    Remove: "إزالة",
    EmptyCart: "السلة فارغة!",
    Subtotal: "المجموع الفرعي",
    DeliveryFee: "رسوم التوصيل",
    FinalTotal: "المبلغ الإجمالي",
    AddToCartToast: "تمت الإضافة إلى السلة!",
    CartEmptyTotal: "الإجمالي: 00.00 ج.م",
    ConfirmEmptyCart: "هل أنت متأكد من إفراغ السلة؟",
    CartEmptied: "تم إفراغ السلة!",
    AddItemDifferentShopTitle: "صنف من متجر آخر",
    AddItemDifferentShopText: "هل تريد إضافة هذا الصنف من متجر آخر؟",
    CannotAddDifferentAreaTitle: "لا يمكن الإضافة",
    CannotAddDifferentAreaText: "لا يمكن إضافة أصناف من منطقة مختلفة.",
    YesAdd: "نعم، أضف",
    Cancel: "إلغاء",
    Ok: "حسناً",
    Currency: "ج.م", 
    CartIsEmpty: "سلة المشتريات فارغة!",
    DefaultShopName: "المتجر",
    HotSpice: "حار",
    PromoCodeTitle: "كود خصم",
    OrderDiscount: "خصم الطلب",
    ShippingDiscount: "خصم التوصيل",
    PromoPlaceholder: "ادخل كود الخصم",
    Apply: "تطبيق",
    PaymentMethodTitle: "طريقة الدفع",
    Cash: "كاش",
    Visa: "فيزا",
    EWallet: "محفظة إلكترونية",
    VodafoneCash: "فودافون كاش",
    WalletNumber: "رقم المحفظة / الحساب اللي هتحول منه",
    PaymentProof: "صورة إثبات التحويل",
    AttachProof: "إرفاق صورة التحويل",
    Extras: "إضافات",
    Notes: "ملاحظات",
    TotalCostLabel: "إجمالي التكلفة:",
    Delivery: "توصيل",
    Pickup: "استلام",
    SubtotalLabel: "المجموع الفرعي:",
    DeliveryLabel: "التوصيل:",
    PickupWarning: "⚠️ الاستلام من المحل يسري على جميع المحلات في الطلب، وغير مسئولين في حال تغيير رأيكم لاحقاً.",
    AddNotesPlaceholder: "أضف ملاحظاتك هنا...",
    ShippingDiscountPlaceholder: "كود خصم التوصيل",
    OrderDiscountPlaceholder: "كود خصم الطلب",
    EnterPromoCodeError: "يرجى إدخال كود الخصم",
    CheckingPromo: "جاري التحقق من",
    PromoAppliedSuccess: "تم تطبيق {0} بنجاح!",
    PromoSavedAmount: "وفرت {0} {1} ({2}%)",
    PromoErrorInvalid: "❌ كود الخصم غير صحيح لنوع الخصم المختار",
    PromoSummaryApplied: "تم تطبيق كود الخصم: وفرت {0} {1} ({2}% خصم على {3})",
    PickupSummaryMsg: "طريقة الاستلام المختارة هي الاستلام من الفرع",
    ChooseLocation: "اختر موقعك",
    WhatsAppTitle: "تواصل معنا عبر واتساب",
    EditEmail: "تعديل البريد الالكتروني",
    EditPassword: "تعديل كلمة المرور",
    OnlyOnePromoClarification: "ℹ️ يمكن تطبيق كود خصم واحد فقط لكل طلب.",
    RemoveCoupon: "إزالة الكود",
    DeliveryMethodTitle: "طريقة الاستلام"
};
